seed: 0
codebase_version: 1.0
headless: true
num_envs: 4096
auto_load_latest: false
checkpoint: null
# project_name: G1Loco
# experiment_name: v0CollNoDR
base_dir: logs
timestamp: ${now:%Y%m%d_%H%M%S}
experiment_dir: ${base_dir}/${project_name}/${timestamp}-${experiment_name}-${log_task_name}-${robot.asset.robot_type}
save_dir: ${experiment_dir}/.hydra
force_flat_terrain: false
use_wandb: false
log_task_name: locomotion
# sim_type: isaacgym
env_spacing: 20
output_dir: ${experiment_dir}/output
eval_overrides:
  headless: false
  num_envs: 1
  auto_load_latest: false
  use_wandb: false
  env:
    config:
      max_episode_length_s: 100000

env:
  config:
    save_rendering_dir: null
    ckpt_dir: null
    robot: ${robot}
    domain_rand: ${domain_rand}
    rewards: ${rewards}
    terrain: ${terrain}
    obs: ${obs}
    env_spacing: 5.0
    max_episode_length_s: 100000
    normalization:
      clip_actions: 100.0
      clip_observations: 100.0
robot:
  dof_obs_size: 27
  number_of_actions: ???
  self_obs_max_coords: ???
  num_bodies: 28
  algo_obs_dim_dict: ???
  key_bodies:
  - l_leg_l6
  - r_leg_l6
  contact_bodies:
  - l_leg_l6
  - r_leg_l6
  foot_name: leg_l6
  init_state:
    pos:
    - 0.0
    - 0.0
    - 0.8
    rot: # XYZW
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    lin_vel:
    - 0.0
    - 0.0
    - 0.0
    ang_vel:
    - 0.0
    - 0.0
    - 0.0
    default_joint_angles:
      # 下肢
      l_leg_1: 0.     # 对应原 left_hip_pitch
      l_leg_2: 0.     # knee
      l_leg_3: 0.
      l_leg_4: 0.     # ankle_pitch
      l_leg_5: 0.
      l_leg_6: 0.
      r_leg_1: 0.
      r_leg_2: 0.
      r_leg_3: 0.
      r_leg_4: 0.
      r_leg_5: 0.
      r_leg_6: 0.
      # 躯干
      torso_1: 0.
      torso_2: 0.
      torso_3: 0.
      # 上肢
      l_arm_1: 0.
      l_arm_2: 0.
      l_arm_3: 0.
      l_arm_4: 0.
      l_arm_5: 0.
      l_arm_6: 0.
      r_arm_1: 0.
      r_arm_2: 0.
      r_arm_3: 0.
      r_arm_4: 0.
      r_arm_5: 0.
      r_arm_6: 0.
  contact_pairs_multiplier: 16
  num_key_bodies: ${len:${robot.key_bodies}}
  mimic_small_marker_bodies: null
  # randomize_link_body_names:
  # - pelvis
  # - left_hip_yaw_link
  # - left_hip_roll_link
  # - left_hip_pitch_link
  # - left_knee_link
  # - right_hip_yaw_link
  # - right_hip_roll_link
  # - right_hip_pitch_link
  # - right_knee_link
  control:
    control_type: P
    stiffness: # [N*m/rad]
      leg_1: 100.0
      leg_2: 100.0
      leg_3: 100.0
      leg_4: 150.0
      leg_5: 40.0
      leg_6: 40.0

      torso: 400.0

      arm_1: 50.0
      arm_2: 50.0
      arm_3: 50.0
      arm_4: 50.0
      arm_5: 20.0
      arm_6: 20.0

    damping: # [N*m/rad]  # [N*m*s/rad]
      leg_1: 2.0
      leg_2: 2.0
      leg_3: 2.0
      leg_4: 4.0
      leg_5: 2.0
      leg_6: 2.0

      torso: 5.0

      arm_1: 2.0
      arm_2: 2.0
      arm_3: 2.0
      arm_4: 2.0
      arm_5: 2.0
      arm_6: 2.0

    action_scale: 0.25
    isaac_pd_scale: false
    clamp_actions: 1.0
    clip_torques: true
    action_clip_value: 100.0
  asset:
    collapse_fixed_joints: true
    replace_cylinder_with_capsule: true
    flip_visual_attachments: false
    armature: 0.001
    thickness: 0.01
    max_angular_velocity: 1000.0
    max_linear_velocity: 1000.0
    density: 0.001
    angular_damping: 0.0
    linear_damping: 0.0
    disable_gravity: null
    fix_base_link: false
    default_dof_drive_mode: 3
    robot_type: ehr03
    urdf_file: ehr03/urdf/ehr03.urdf
    usd_file: g1/${robot.asset.robot_type}.usd
    xml_file: ehr03/urdf/ehr03_simplifed_mjx.xml
    asset_root: description/robots
    self_collisions: 0
    filter_ints: null
  actions_dim: 27
  lower_body_actions_dim: 15
  upper_body_actions_dim: 12
  policy_obs_dim: -1
  critic_obs_dim: -1
  num_feet: 2
  right_foot_name: r_leg_l6
  left_foot_name: l_leg_l6
  knee_name: leg_l4
  has_torso: true
  torso_name: torso
  has_upper_body_dof: true
  dof_names:
  - l_leg_1
  - l_leg_2
  - l_leg_3
  - l_leg_4
  - l_leg_5
  - l_leg_6
  - r_leg_1
  - r_leg_2
  - r_leg_3
  - r_leg_4
  - r_leg_5
  - r_leg_6
  - torso_1
  - torso_2
  - torso_3
  - l_arm_1
  - l_arm_2
  - l_arm_3
  - l_arm_4
  - l_arm_5
  - l_arm_6
  - r_arm_1
  - r_arm_2
  - r_arm_3
  - r_arm_4
  - r_arm_5
  - r_arm_6

  upper_dof_names:
  - l_arm_1
  - l_arm_2
  - l_arm_3
  - l_arm_4
  - l_arm_5
  - l_arm_6
  - r_arm_1
  - r_arm_2
  - r_arm_3
  - r_arm_4
  - r_arm_5
  - r_arm_6
  upper_left_arm_dof_names:
  - l_arm_1
  - l_arm_2
  - l_arm_3
  - l_arm_4
  - l_arm_5
  - l_arm_6
  upper_right_arm_dof_names:
  - r_arm_1
  - r_arm_2
  - r_arm_3
  - r_arm_4
  - r_arm_5
  - r_arm_6
  lower_dof_names:
  - l_leg_1
  - l_leg_2
  - l_leg_3
  - l_leg_4
  - l_leg_5
  - l_leg_6
  - r_leg_1
  - r_leg_2
  - r_leg_3
  - r_leg_4
  - r_leg_5
  - r_leg_6
  - torso_1
  - torso_2
  - torso_3
  waist_dof_names:
  - torso_1
  - torso_2
  - torso_3
  dof_pos_lower_limit_list:
  - -1.57
  - -0.20
  - -1.57
  - -0.523
  - -0.84
  - -0.45
  - -1.57
  - -1.57
  - -1.57
  - -0.523
  - -0.84
  - -0.45
  - -2.10
  - -0.523
  - -0.523
  - -3.58
  - -0.174
  - -1.57
  - -1.74
  - -0.37
  - -0.37
  - -3.58
  - -2.966
  - -1.57
  - -1.74
  - -0.37
  - -0.385
  dof_pos_upper_limit_list:
  - 1.57
  - 1.57
  - 1.57
  - 1.57
  - 0.70
  - 0.45
  - 1.57
  - 0.20
  - 1.57
  - 1.57
  - 0.70
  - 0.45
  - 2.10
  - 0.523
  - 0.523
  - 2.71
  - 2.966
  - 1.57
  - 0.785
  - 0.37
  - 0.385
  - 2.71
  - 0.174
  - 1.57
  - 0.785
  - 0.37
  - 0.37
  dof_vel_limit_list:
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 20
  - 20
  - 3
  - 20
  - 20
  - 3
  - 20
  - 20
  - 3
  - 20
  - 20
  - 3
  dof_effort_limit_list:
  - 100
  - 100
  - 100
  - 100
  - 50
  - 50
  - 100
  - 100
  - 100
  - 100
  - 50
  - 50
  - 100
  - 100
  - 100
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  dof_armature_list:
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.04
  - 0.03
  - 0.03
  - 0.03
  dof_joint_friction_list:
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  - 0.03
  body_names:
  - base_link
  - l_leg_l1
  - l_leg_l2
  - l_leg_l3
  - l_leg_l4
  - l_leg_l5
  - l_leg_l6
  - r_leg_l1
  - r_leg_l2
  - r_leg_l3
  - r_leg_l4
  - r_leg_l5
  - r_leg_l6
  - torso_l1
  - torso_l2
  - torso_l3
  - l_arm_l1
  - l_arm_l2
  - l_arm_l3
  - l_arm_l4
  - l_arm_l5
  - l_arm_l6
  - r_arm_l1
  - r_arm_l2
  - r_arm_l3
  - r_arm_l4
  - r_arm_l5
  - r_arm_l6
  terminate_after_contacts_on:
  - base_link
  - leg_l1
  - leg_l2
  - arm_l1
  - arm_l2
  penalize_contacts_on:
  - base_link
  - leg_l1
  - leg_l2
  - arm_l1
  - arm_l2
  - torso
  - arm_l3
  - arm_l4
  motion:
    motion_file: ???
    motion_lib_type: WJX
    asset:
      assetRoot: description/robots/ehr03/urdf
      assetFileName: ehr03_simplifed_mjx.xml
    humanoid_type: ehr03
    bias_offset: false
    has_self_collision: true
    has_mesh: false
    has_jt_limit: false
    has_dof_subset: true
    has_upright_start: true
    has_smpl_pd_offset: false
    remove_toe: false
    motion_sym_loss: false
    sym_loss_coef: 1
    big_ankle: true
    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: false
    masterfoot: false
    freeze_toe: false
    freeze_hand: false
    box_body: true
    real_weight: true
    real_weight_porpotion_capsules: true
    real_weight_porpotion_boxes: true
    body_names:
    - base_link
    - l_leg_l1
    - l_leg_l2
    - l_leg_l3
    - l_leg_l4
    - l_leg_l5
    - l_leg_l6
    - r_leg_l1
    - r_leg_l2
    - r_leg_l3
    - r_leg_l4
    - r_leg_l5
    - r_leg_l6
    - torso_l1
    - torso_l2
    - torso_l3
    - l_arm_l1
    - l_arm_l2
    - l_arm_l3
    - l_arm_l4
    - l_arm_l5
    - l_arm_l6
    - r_arm_l1
    - r_arm_l2
    - r_arm_l3
    - r_arm_l4
    - r_arm_l5
    - r_arm_l6
    limb_weight_group:
    - - l_leg_l1
      - l_leg_l2
      - l_leg_l3
      - l_leg_l4
      - l_leg_l5
      - l_leg_l6
    - - r_leg_l1
      - r_leg_l2
      - r_leg_l3
      - r_leg_l4
      - r_leg_l5
      - r_leg_l6
    - - base_link
      - torso_l1
      - torso_l2
      - torso_l3
    - - l_arm_l1
      - l_arm_l2
      - l_arm_l3
      - l_arm_l4
      - l_arm_l5
      - l_arm_l6
    - - r_arm_l1
      - r_arm_l2
      - r_arm_l3
      - r_arm_l4
      - r_arm_l5
      - r_arm_l6
    dof_names:
    - l_leg_1
    - l_leg_2
    - l_leg_3
    - l_leg_4
    - l_leg_5
    - l_leg_6
    - r_leg_1
    - r_leg_2
    - r_leg_3
    - r_leg_4
    - r_leg_5
    - r_leg_6
    - torso_1
    - torso_2
    - torso_3
    - l_arm_1
    - l_arm_2
    - l_arm_3
    - l_arm_4
    - l_arm_5
    - l_arm_6
    - r_arm_1
    - r_arm_2
    - r_arm_3
    - r_arm_4
    - r_arm_5
    - r_arm_6
    right_foot_name: r_leg_l6
    left_foot_name: l_leg_l6
    nums_extend_bodies: 3
    extend_config:
    - joint_name: left_hand_link
      parent_name: l_arm_l6
      pos:
      - -0.1
      - 0.0
      - 0.0
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    - joint_name: right_hand_link
      parent_name: r_arm_l6
      pos:
      - -0.1
      - 0.0
      - 0.0
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    - joint_name: head_link
      parent_name: base_link
      pos:
      - 0.0
      - 0.0
      - 0.42
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    motion_tracking_link:
    - left_hand_link
    - right_hand_link
    - head_link
    lower_body_link:
    - base_link
    - l_leg_l1
    - l_leg_l2
    - l_leg_l3
    - l_leg_l4
    - l_leg_l5
    - l_leg_l6
    - r_leg_l1
    - r_leg_l2
    - r_leg_l3
    - r_leg_l4
    - r_leg_l5
    - r_leg_l6
    - torso_l1
    - torso_l2
    - torso_l3
    upper_body_link:
    - l_arm_l1
    - l_arm_l2
    - l_arm_l3
    - l_arm_l4
    - l_arm_l5
    - l_arm_l6
    - r_arm_l1
    - r_arm_l2
    - r_arm_l3
    - r_arm_l4
    - r_arm_l5
    - r_arm_l6
    pelvis_link: base_link
    base_link: torso_l3
    hips_link:
    - l_leg_l1
    - l_leg_l2
    - l_leg_l3
    - r_leg_l1
    - r_leg_l2
    - r_leg_l3
    joint_matches:
    - - base_link
      - Pelvis
    - - l_leg_l3
      - L_Hip
    - - l_leg_l4
      - L_Knee
    - - l_leg_l6
      - L_Ankle
    - - r_leg_l3
      - R_Hip
    - - r_leg_l4
      - R_Knee
    - - r_leg_l6
      - R_Ankle
    - - l_arm_l1
      - L_Shoulder
    - - l_arm_l4
      - L_Elbow
    - - left_hand_link
      - L_Hand
    - - r_arm_l1
      - R_Shoulder
    - - r_arm_l4
      - R_Elbow
    - - right_hand_link
      - R_Hand
    - - head_link
      - Head
    smpl_pose_modifier:
    - Pelvis: '[np.pi/2, 0, np.pi/2]'
    - L_Shoulder: '[0, 0, -np.pi/2]'
    - R_Shoulder: '[0, 0, np.pi/2]'
    - L_Elbow: '[0, -np.pi/2, 0]'
    - R_Elbow: '[0, np.pi/2, 0]'
    visualization:
      customize_color: true
      marker_joint_colors:
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0.929
        - 0.867
        - 0.437
      - - 0
        - 0.351
        - 0.613
      - - 0
        - 0.351
        - 0.613
      - - 0
        - 0.351
        - 0.613
      - - 0
        - 0.351
        - 0.613
      - - 0
        - 0.351
        - 0.613
      - - 0
        - 0.351
        - 0.613
      - - 0
        - 0.351
        - 0.613
obs:
  obs_dict:
    actor_obs:
    - base_ang_vel
    - projected_gravity
    - command_lin_vel
    - command_ang_vel
    - dof_pos
    - dof_vel
    - actions
    - short_history
    critic_obs:
    - base_lin_vel
    - base_ang_vel
    - projected_gravity
    - command_lin_vel
    - command_ang_vel
    - dof_pos
    - dof_vel
    - actions
    - short_history
  obs_auxiliary:
    short_history:
      base_ang_vel: 5
      projected_gravity: 5
      dof_pos: 5
      dof_vel: 5
      actions: 5
      command_lin_vel: 5
      command_ang_vel: 5
  obs_scales:
    base_lin_vel: 2.0
    base_ang_vel: 0.25
    projected_gravity: 1.0
    command_lin_vel: 1.0
    command_ang_vel: 1.0
    dof_pos: 1.0
    dof_vel: 0.05
    history: 1.0
    short_history: 1.0
    actions: 1.0
  noise_scales:
    base_lin_vel: 0.0
    base_ang_vel: 0.0
    projected_gravity: 0.0
    command_lin_vel: 0.0
    command_ang_vel: 0.0
    dof_pos: 0.0
    dof_vel: 0.0
    actions: 0.0
    history: 0.0
    short_history: 0.0
  add_noise_currculum: false
  noise_initial_value: 0.05
  noise_value_max: 1.0
  noise_value_min: 1.0e-05
  soft_dof_pos_curriculum_degree: 1.0e-05
  soft_dof_pos_curriculum_level_down_threshold: 100
  soft_dof_pos_curriculum_level_up_threshold: 900
  obs_dims:
  - base_lin_vel: 3
  - base_ang_vel: 3
  - projected_gravity: 3
  - command_lin_vel: 2
  - command_ang_vel: 1
  - dof_pos: ${robot.dof_obs_size}
  - dof_vel: ${robot.dof_obs_size}
  - actions: ${robot.dof_obs_size}
  post_compute_config: {}
